from sys import argv
import os

class GenerateAST:
    def __init__(self, ast):
        self.ast = ast

    def defineAST(self, output, baseName, types):
        path = os.path.join(output, f"{baseName}.py")
        with open(path, "w") as f:
            f.write(f"// Generated by Pilox langauge\n")
            f.write(f"from typing import List,  Any\n")
            
            f.write(f"class {baseName}:\n")
            f.write(f"  \"\"\"Base class for all {baseName} expression nodes in the AST.\"\"\"\n")
            f.write(f"  pass\n\n")
            
            
            f.close()
        
    def main(self): 
        if len(argv) != 2:
            print("Usage: python3 pilox.py <source>")
            exit(64)
            
        output = argv[1]
        self.defineAST(output, "Expr", ["Binary", "Grouping", "Literal", "Unary"])
