from sys import argv
import os

class GenerateAST:
    def __init__(self, ast=None):
        self.ast = ast

    def defineAST(self, output_dir, baseName, types):
        path = os.path.join(output_dir, f"{baseName}.py")
        with open(path, "w") as f:
            f.write(f"# Generated by Pilox language\n")
            f.write(f"from typing import Any\n")
            f.write(f"from TokenType import Token\n\n")

            f.write(f"class {baseName}:\n")
            f.write(f"    \"\"\"Base class for all {baseName} expression nodes.\"\"\"\n")
            f.write(f"    def accept(self, visitor):\n")
            f.write(f"        \"\"\"Abstract method to accept a visitor.\"\"\"\n")
            f.write(f"        raise NotImplementedError(\"Subclasses must implement abstract method\")\n\n")
            
            self.defineVisitor(f, baseName, types)
            
            for type_def in types:
                className, fields_raw = map(str.strip, type_def.split(":"))
                fields = [f.strip() for f in fields_raw.split(",")]
                self.defineType(f, baseName, className, fields)

    def defineVisitor(self, f, baseName, types):
        f.write(f"class {baseName}Visitor:\n")
        f.write(f"    \"\"\"Visitor interface for {baseName} nodes.\"\"\"\n")
        for type_def in types:
            typeName, _ = map(str.strip, type_def.split(":"))
            f.write(f"    def visit_{typeName.lower()}{baseName.lower()}(self, {baseName.lower()}: '{typeName}') -> Any:\n")
            f.write(f"        \"\"\"Visit a {typeName} node.\"\"\"\n")
            
    def defineType(self, f, baseName, className, fields):
        f.write(f"class {className}({baseName}):\n")
        f.write(f"    \"\"\"{className} node in the AST.\"\"\"\n")
        f.write("\n    def accept(self, visitor):\n")
        f.write(f"        return visitor.visit_{className.lower()}{baseName.lower()}(self)\n")
        
        for field in fields:
            name, typ = map(str.strip, field.split(" "))
            f.write(f"    {name}: {typ}\n")

        param_names = [field.split(" ")[0] for field in fields]
        f.write(f"\n    def __init__(self, {', '.join(param_names)}):\n")
        
        for field in fields:
            name = field.split(" ")[0]
            f.write(f"        self.{name} = {name}\n")
        f.write("\n")

    def main(self):
        if len(argv) != 2:
            print("Usage: python3 pilox.py <output_directory>")
            exit(64)

        output_dir = argv[1]
        self.defineAST(output_dir, "Expr", [
            "Binary : left Expr, operator Token, right Expr",
            "Grouping : expression Expr",
            "Literal : value Any",
            "Unary : operator Token, right Expr"
        ])

if __name__ == "__main__":
    GenerateAST().main()
